### ISSUE TITLE
Activating FakeGapps breaks Netflix

### ISSUE THREAD

**Issue by eku** [thermatk/FakeGApps#46]
My phone is running `microG Installer Revived` via `Magisk` and `FakeGApps` via `LSPosed_mod`.

If FakeGApps is actived, microG passes self-test. But Netflix crashes with

```
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge: Crash unexpectedly: java.lang.UnsatisfiedLinkError: dlopen failed: library "libcronet.102.0.5005.125.so" not found
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at java.lang.Runtime.loadLibrary0(Runtime.java:1077)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at java.lang.Runtime.loadLibrary0(Runtime.java:998)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at java.lang.System.loadLibrary(System.java:1661)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at org.chromium.net.impl.CronetLibraryLoader.ensureInitialized(CronetLibraryLoader.java:71)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at org.chromium.net.impl.CronetUrlRequestContext.<init>(CronetUrlRequestContext.java:168)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at org.chromium.net.impl.NativeCronetEngineBuilderImpl.build(NativeCronetEngineBuilderImpl.java:32)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at org.chromium.net.ExperimentalCronetEngine$Builder.build(:474)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at o.aHK.a(:73)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at o.aHN.d(:55)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at o.aHJ.<init>(:53)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at com.netflix.mediaclient.service.NetflixService.onCreate(:430)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4555)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.os.Handler.dispatchMessage(Handler.java:106)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.os.Looper.loopOnce(Looper.java:201)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.os.Looper.loop(Looper.java:288)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at android.app.ActivityThread.main(ActivityThread.java:7941)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at java.lang.reflect.Method.invoke(Native Method)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
03-01 19:01:06.637 13997 13997 I LSPosed-Bridge:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)
```

Any idea why this only happens if FakeGapps is active?

**Comment by loftenth-eepy** [comment]
having same problem with claude
